export const EASTER_EGGS = [
  // Emojis
  { type: 'emoji', content: '🎄' },
  { type: 'emoji', content: '🎅' },
  { type: 'emoji', content: '🤶' },
  { type: 'emoji', content: '🦌' },
  { type: 'emoji', content: '❄️' },
  { type: 'emoji', content: '⛄' },
  { type: 'emoji', content: '🎁' },
  { type: 'emoji', content: '🔔' },
  { type: 'emoji', content: '✨' },
  { type: 'emoji', content: '⭐' },
  { type: 'emoji', content: '🍪' },
  { type: 'emoji', content: '🥛' },
  { type: 'emoji', content: '🎀' },
  { type: 'emoji', content: '🕯️' },
  { type: 'emoji', content: '🎵' },

  // Frases curtas divertidas
  { type: 'frase', content: 'Ho Ho Ho! 🎅' },
  { type: 'frase', content: 'Feliz Natal! 🎄' },
  { type: 'frase', content: 'Código Natalino' },
  { type: 'frase', content: 'Debug com Alegria' },
  { type: 'frase', content: 'Deploy em Paz' },
  { type: 'frase', content: 'Git Commit' },
  { type: 'frase', content: 'Status: Merry' },
  { type: 'frase', content: 'Console.log(Alegria)' },
  { type: 'frase', content: 'null !== Natal' },
  { type: 'frase', content: 'if(Navidad) ...' },

  { type: 'image', content: '/easter-eggs/adailton-1.png' },
  { type: 'image', content: '/easter-eggs/eraldo-1.png' },
  { type: 'image', content: '/easter-eggs/igor-1.png' },
  { type: 'image', content: '/easter-eggs/igor-2.png' },
  { type: 'image', content: '/easter-eggs/igor-3.png' },
  { type: 'image', content: '/easter-eggs/isaque-1.png' },
  { type: 'image', content: '/easter-eggs/isaque-2.png' },
  { type: 'image', content: '/easter-eggs/jeffe-1.png' },
  { type: 'image', content: '/easter-eggs/magro-1.png' },
  { type: 'image', content: '/easter-eggs/scheibe-1.png' },
  { type: 'image', content: '/easter-eggs/scheibe-2.png' },
  { type: 'image', content: '/easter-eggs/scheibe-3.png' },
  { type: 'image', content: '/easter-eggs/vini-a-1.png' },
];

export type EasterEgg = (typeof EASTER_EGGS)[number];
